version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-deps:
        dependency-type: development
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    groups:
      actions:
        update-types:
          - patch
          - minor
          - major
